import './globals.css';
import '@repo/ui/styles.css';
import type { Metadata } from 'next';
import { gowunDodum } from '@/public/fonts';
import { Navigation } from '@components/navigation';

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={gowunDodum.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
