import type { CareerMap } from '@/interface';

export const CareerList = [
  {
    name: '하이퍼 커뮤니티',
    href: 'https://2d0.notion.site/2bac18a8bfff4116a0be1dfcdc33b52c?pvs=4',
    position: '프론트 개발자',
    scope: ['프론트 개발', '퍼블리싱', 'UI/UX 디자인'],
    startDate: '2024.04',
    endDate: '재직중',
    stack: [
      'Next.js14',
      'Supabase',
      'TypeScript',
      'Vercel',
      'TailwindCSS',
      'Figma',
    ],
    work: [
      '홈페이지 및 랜딩 페이지 UI 개발',
      '로아챗 컴포넌트 UI 개발',
      'UI/UX 디자인 작업',
    ],
  },
  {
    name: '(주)유니버스',
    href: 'https://2d0.notion.site/184c46f44b9f80bbb123c6db829a15b6?pvs=4',
    position: '프론트 개발자',
    scope: ['프론트 개발', '퍼블리싱'],
    startDate: '2023.10',
    endDate: '2024.02',
    stack: [
      'Next.js14',
      'React',
      'Vue',
      'Supabase',
      'JavaScript',
      'TypeScript',
      'StyledComponents',
      'SCSS',
      'TailwindCSS',
      'Figma',
    ],
    work: [
      '안면인식 솔루션 API 연결 및 UI 개발',
      '몽골 방법 사업 현지화 UI 개발',
      'UI/UX 디자인 작업',
    ],
  },
  {
    name: '(주)잇팩',
    href: 'https://2d0.notion.site/71e1e40e15dc49a68d0ce974894f6fe9?pvs=4',
    position: '퍼블리셔',
    scope: ['퍼블리싱', 'UI/UX 디자인'],
    startDate: '2023.05',
    endDate: '2023.08',
    stack: ['React', 'SCSS', 'Figma'],
    work: [
      '솔루션 프로젝트의 UI/UX 프로토타입 툴을 적용한 디자인',
      '아이콘 퍼블리싱',
      '프론트에 능숙하지 못한 사원에게 지도 및 가이드 제시',
    ],
  },
  {
    name: '시안',
    href: 'https://2d0.notion.site/e02b6b2602fe4247aa39810459207f93?pvs=4',
    position: '프론트 개발자',
    scope: ['프론트 개발', '퍼블리싱'],
    startDate: '2022.09',
    endDate: '2023.04',
    stack: ['PHP', 'HTML', 'CSS', 'JavaScript', 'jQuery', 'Figma'],
    work: [
      '퍼블리싱 및 API 연결(CRUD)을 제외한 프론트 개발',
      'UI/UX 디자인 및 간단한 아이콘 제작',
    ],
  },
  {
    name: '시간여행티비',
    href: 'https://2d0.notion.site/2cd1dbe50fad4851b1674857a77abc1e?pvs=4',
    position: '퍼블리셔',
    scope: ['퍼블리싱', 'UI/UX 디자인'],
    startDate: '2022.03',
    endDate: '2022.07',
    stack: ['Nuxt.js', 'JavaScript', 'SCSS', 'Figma'],
    work: [
      '퍼블리싱 및 API 연결(CRUD)을 제외한 프론트 개발',
      'UI/UX 디자인 및 간단한 아이콘 제작',
    ],
  },
  {
    name: '위즈메이드',
    href: 'https://2d0.notion.site/d255be43e4ea4000a0c34cacc4f8c3e6?pvs=4',
    position: '퍼블리셔',
    scope: ['퍼블리싱', 'UI/UX 디자인'],
    startDate: '2021.06',
    endDate: '2022.06',
    stack: ['PHP', 'HTML', 'CSS', 'React', 'Vue', 'jQuery', 'SCSS', 'Figma'],
    work: [
      '주로 cafe24 스킨을 커스텀 하여 쇼핑몰 페이지를 개발',
      'jQuery를 사용해 가격 할인율 계산, 별점 API 연결 후 디자인 커스텀 등 간단한 기능 및 동작을 구현',
    ],
  },
  {
    name: '아이디자인닷컴',
    href: 'https://2d0.notion.site/be72a1d3fe00475cbaff3a7de9e942f7?pvs=4',
    position: '퍼블리셔',
    scope: ['퍼블리싱'],
    startDate: '2020.11',
    endDate: '2021.06',
    stack: ['PHP', 'HTML', 'CSS', 'jQuery'],
    work: [
      '영카트 스킨 커스텀',
      '그누보드 스킨 커스텀',
      '배너 및 상세 페이지 제작',
    ],
  },
] as CareerMap[];
