import type { ProjectMap } from '@/interface';

export const ProjectList: Array<ProjectMap> = [
  {
    name: '퍼피티아이',
    company: '개인 프로젝트',
    href: 'https://2d0.notion.site/7c6cc84f2a504730ae377d2fbcee8b14?pvs=4',
    site: 'https://puppy-ti.maketree.net/',
    startDate: '2023.01',
    endDate: '2024.11',
    period: '약 1년 8개월',
    desc: '내가 키우는 강아지는 어떤 성향을 가지고 있는지 테스트 할 수 있는 사이트 \n react → next.13, typescript → next.js 14, supabase → turborepo 로 4번째 리팩터링으로 완성 하였습니다.',
    stack: [
      'Next.js14',
      'React',
      'TypeScript',
      'JavaScript',
      'Supabase',
      'Turborepo',
      'Vercel',
      'TailwindCSS',
      'StyledComponents',
      'Figma',
    ],
    imageName: 'puppy-ti',
    scope: ['기획 및 총괄', '프론트 개발', '백엔드 개발', 'UI/UX 디자인'],
  },
  {
    name: '내면의 색',
    company: '개인 프로젝트',
    href: 'https://2d0.notion.site/183c46f44b9f80d4915ee59b92ef6f53?pvs=4',
    site: 'https://inner-color.maketree.net/',
    startDate: '2024.11',
    endDate: '2024.11',
    period: '약 2주',
    desc: `질문을 통해 본인의 성향을 판단하여 어울리는 색을 결과로 출력해주는 사이트\n
    퍼피티아이와 똑같은 스택으로 작업했습니다. (모노레포)`,
    stack: [
      'Next.js14',
      'TypeScript',
      'Supabase',
      'Turborepo',
      'Vercel',
      'TailwindCSS',
      'Figma',
    ],
    imageName: 'inner-color',
    scope: ['기획 및 총괄', '프론트 개발', 'UI/UX 디자인'],
  },
  {
    name: '하이퍼 커뮤니티 홈페이지',
    company: '하이퍼 커뮤니티',
    href: 'https://2d0.notion.site/184c46f44b9f80709d0dcc18531f973b?pvs=4',
    site: 'https://hypr.community/',
    startDate: '2024.12',
    endDate: '2025.01',
    period: '약 2주',
    desc: '하이퍼 커뮤니티의 홈페이지 입니다.',
    stack: [
      'Next.js14',
      'TypeScript',
      'Supabase',
      'Turborepo',
      'Vercel',
      'TailwindCSS',
    ],
    imageName: 'hypr-site',
    scope: ['프론트 개발', 'UI/UX 디자인'],
  },
  {
    name: '우주',
    company: '(주)유니버스',
    href: 'https://2d0.notion.site/f75ccec60a3d4788b8802487046f2d05?pvs=4',
    site: 'https://2d0.notion.site/3976e02f3a91445496453396c58478de?pvs=4',
    startDate: '2023.10',
    endDate: '2023.12',
    period: '약 3개월',
    desc: '얼굴 사진을 찍어 원하는 유명인과 매칭하여 나온 점수로 순위를 매기는 이벤트 페이지',
    stack: ['React', 'TypeScript', 'StyledComponents', 'Figma'],
    imageName: 'would-u',
    scope: ['프론트 개발', 'UI/UX 디자인'],
  },
  {
    name: '스페이스 가드 (관리자 용)',
    company: '(주)유니버스',
    href: 'https://2d0.notion.site/487edd1c1d2b401ab3ffae49c5e1031e?pvs=4',
    startDate: '2024.01',
    endDate: '2024.02',
    period: '약 3주',
    desc: '얼굴 인식을 통한 방범 솔루션을 구독한 유치원 혹은 학교 등의 업체에서 고객들의 정보를 등록 및 수정하고 데이터 사용량을 확인할 수 있는 대시보드 관리자 페이지',
    stack: ['Next.js14', 'TypeScript', 'Supabase', 'TailwindCSS', 'Figma'],
    imageName: 'spaceguard-owner',
    scope: ['프론트 개발', 'UI/UX 디자인'],
  },
  {
    name: '스페이스 가드 (보호자 용)',
    company: '(주)유니버스',
    href: 'https://2d0.notion.site/1d217cfec0b24d66b8004abbf4f20f1c?pvs=4',
    startDate: '2024.01',
    endDate: '2024.01',
    period: '약 1개월',
    desc: '얼굴 인식을 통한 방범 솔루션을 구독한 유치원 혹은 학교의 고객(보호자)들이 직접 얼굴 정보 등록 및 수정 등의 관리를 할 수 있도록 개발한 시스템',
    stack: ['Next.js14', 'TypeScript', 'Supabase', 'StyledComponents', 'Figma'],
    imageName: 'spaceguard-customer',
    scope: ['프론트 개발', 'UI/UX 디자인'],
  },
  {
    name: '민트 오션',
    company: '(주)시간여행티비',
    href: 'https://2d0.notion.site/951192f9e668453c8739ac8a90e498ca?pvs=4',
    site: 'https://2d0.github.io/vue-project/',
    startDate: '2022.03',
    endDate: '2022.06',
    period: '약 3개월',
    desc: 'nft 거래소',
    stack: ['Nuxt.js', 'Vue', 'JavaScript', 'SCSS', 'Figma'],
    imageName: 'mint-ocean',
    scope: ['프론트 개발', 'UI/UX 디자인'],
  },
  {
    name: '강남콩',
    company: '(주)위즈메이드',
    href: 'https://2d0.notion.site/c39b7bb2e27143bfa73bd53e8b3c4759?pvs=4',
    site: 'https://gangnamkong.co.kr/',
    startDate: '2021.08',
    endDate: '2021.11',
    period: '약 3개월',
    desc: '여러 브랜드의 물 및 해외 식품 등 한국에서 흔하지 않은 식품을 파는 쇼핑몰',
    stack: ['HTML', 'Cafe24Module', 'jQuery', 'CSS'],
    imageName: 'gangnamkong',
    scope: ['프론트 개발'],
  },
  {
    name: '술밤',
    company: '시안',
    href: 'https://2d0.notion.site/24c7b29b83c34beaaac45d987d3932a7?pvs=4',
    startDate: '2023.01',
    endDate: '2023.02',
    period: '약 2주',
    desc: '카테고리를 선택해 원하는 술집 위치를 찾을 수 있는 술집 추천 커뮤니티',
    stack: ['PHP', 'jQuery', 'CSS', 'Figma'],
    imageName: 'sulbam',
    scope: ['프론트 개발', 'UI/UX 디자인'],
  },
  {
    name: '업페이지',
    company: '시안',
    href: 'https://2d0.notion.site/164026ca0d1343ee82a3e5c6737b13a6?pvs=4',
    site: 'https://www.uppage.com/',
    startDate: '2022.10',
    endDate: '2022.11',
    period: '약 2주',
    desc: '클릭만으로 홈페이지 만들기 솔루션 제공',
    stack: ['PHP', 'jQuery', 'CSS'],
    imageName: 'uppage',
    scope: ['프론트 개발'],
  },
  {
    name: '두바잉',
    company: '시안',
    href: 'https://2d0.notion.site/bf47d0b2776245688adfb6445a949f4c?pvs=4',
    site: 'https://www.doobuying.com/',
    startDate: '2023.01',
    endDate: '2023.04',
    period: '약 3개월',
    desc: 'sns 커뮤니티와 쇼핑몰을 합쳐놓은 하이브리드 쇼핑몰',
    stack: ['PHP', 'jQuery', 'CSS'],
    imageName: 'doobuying',
    scope: ['프론트 개발'],
  },
  {
    name: '어드레스 골프',
    company: '(주)위즈메이드',
    href: 'https://2d0.notion.site/012e2b4f20884407b61384f0b2ad7ec7?pvs=4',
    site: 'https://adressgolf.com/',
    startDate: '2021.12',
    endDate: '2022.02',
    period: '약 2개월',
    desc: '골프복 렌탈 서비스 제공 및 골프 관련 쇼핑몰',
    stack: ['PHP', 'jQuery', 'CSS'],
    imageName: 'adress-golf',
    scope: ['프론트 개발'],
  },
  {
    name: '오스빈',
    company: '(주)위즈메이드',
    href: 'https://2d0.notion.site/dfe70e047b1241629d8aaa5069200d98?pvs=4',
    startDate: '2021.12',
    endDate: '2022.01',
    period: '약 2주',
    desc: '빈티지 옷들을 컨셉으로 한 sns 커뮤니티와 쇼핑몰을 합쳐놓은 하이브리드 쇼핑몰 어플리케이션',
    stack: ['React', 'JavaScript', 'PHP', 'CSS'],
    imageName: 'osbin',
    scope: ['프론트 개발'],
  },
  {
    name: 'SMART-AICC',
    company: '(주)잇팩',
    href: 'https://2d0.notion.site/SMART-AICC-f478ead658844628b91d1c2e8b0477a7?pvs=4',
    startDate: '2023.05',
    endDate: '2023.08',
    period: '약 3개월',
    desc: `카카오톡, 게시판, 메일 등 상담 요청을 한 페이지에서 옴니버스 형식으로 관리하고
고객과의 통화를 음성인식을 통해 실시간으로 채팅으로 보여주는 ai 솔루션`,
    stack: ['React', 'JavaScript', 'SCSS', 'Figma'],
    imageName: 'smart-aicc',
    scope: ['프론트 개발', 'UI/UX 디자인'],
  },
  {
    name: '2021 웹 퍼블리셔 포트폴리오',
    company: '개인 프로젝트',
    href: 'https://2d0.notion.site/2021-874db80518e648b0b7f77318b455e124?pvs=4',
    site: 'https://2d0.github.io/portfolio-publisher/',
    startDate: '2021.05',
    endDate: '2021.06',
    period: '약 2주',
    desc: '2021년도에 제작한 웹 퍼블리셔 포트폴리오',
    stack: ['HTML', 'jQuery', 'CSS'],
    imageName: 'portfolio-publisher',
    scope: ['기획 및 총괄', '프론트 개발', 'UI/UX 디자인'],
  },
];
